Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.9/site-packages/flask/app.py\", line 1509, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/usr/local/lib/python3.9/site-packages/concordapi/handlers/frontapihandler.py\", line 196, in pre_handle\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/concordapi/handlers/frontapihandler.py\", line 181, in pre_handle\n    result = self.handle(call_context, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/concordcommon/signalfxmonitor/sfxwrappers.py\", line 32, in wrapper\n    return new_func(*args, **kw)\n  File \"/usr/local/lib/python3.9/site-packages/statsd/client/timer.py\", line 38, in _wrapped\n    return f(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/concordapi/handlers/decorator/resourcechecker.py\", line 103, in wrapper\n    rt = func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/concordapi/handlers/impl/pipetemplatecreatorpublic.py\", line 84, in handle\n    pipe_utils.validate_pipe_resources(\n  File \"/usr/local/lib/python3.9/site-packages/concordapi/utils/pipe_utils.py\", line 94, in validate_pipe_resources\n    resource = ParamHandler.get_param(\"remote_name\", dict, jobs)\n  File \"/usr/local/lib/python3.9/site-packages/concordcommon/restapi/paramhandler.py\", line 55, in get_param\n    cls._check_dict_param(param_name, param_type, param_dict)\n  File \"/usr/local/lib/python3.9/site-packages/concordcommon/restapi/paramhandler.py\", line 36, in _check_dict_param\n    raise ExceptionFactory(cls).invalid_parameter_value(f\"Invalid value for {param_name}\")\nconcordcommon.exceptions.concordexception.ConcordException: Invalid value for remote_name\n

